### ISSUE TITLE
Accept error: could not accept new connection java.io.IOException: Too many open files

### ISSUE THREAD

**Issue by liu-hongwei** [akka/akka.github.com#185]
hi,

i am investigating below error which originally posted here https://github.com/spark-jobserver/spark-jobserver/issues/55

i am using spark job server, which uses the spray underneath to provide REST api server support.

but when we send thousands simultaneously requests to the REST api server, it crashed with below errors. 

so there must be some limitation in the Spray code which restricts the number of concurrent TCP connections.

how can we fix this?

thanks in advance 

[2015-01-27 16:40:59,292] ERROR akka.io.TcpListener [] [akka://JobServer/system/IO-TCP/selectors/$a/0] - Accept error: could not accept new connection
java.io.IOException: Too many open files
at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:241)
at akka.io.TcpListener.acceptAllPending(TcpListener.scala:96)
at akka.io.TcpListener$$anonfun$bound$1.applyOrElse(TcpListener.scala:76)
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
at akka.actor.ActorCell.invoke(ActorCell.scala:456)
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
at akka.dispatch.Mailbox.run(Mailbox.scala:219)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by drewhk** [comment]
Hi,

Have you tried playing with the settings

   akka.actor.io.tcp.number-of-selectors

and

   akka.actor.io.tcp.max-channels

see: http://doc.akka.io/docs/akka/2.3.9/general/configuration.html for
details.

-Endre

**Comment by drewhk** [comment]
Btw, this is the Akka website issue tracker, you want to use this one: https://github.com/akka/akka/issues
